package com.raka.audiorecorder.data.database

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Table of Audio Record
 * @param id is primary key and autogenerated
 * @param filename type String
 * @param filepath type String
 * @param duration type String
 */
@Entity(tableName = "audio_records")
data class AudioRecord(
    val filename: String,
    val filepath: String,
    val duration: String,
) {
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0
}
